import crypto from 'node:crypto';
import type { TunnelConfig, TunnelPlan } from './types.js';
import { validateTunnelConfig } from './validation.js';
export function createTunnelPlan(input: TunnelConfig): TunnelPlan {
  const validation = validateTunnelConfig(input); const c = validation.normalized ?? input;
  const argv = c.operation === 'quick' ? ['tunnel', '--url', c.localUrl] : c.operation === 'create' ? ['tunnel', 'create', c.tunnelName ?? ''] : ['tunnel', c.operation, c.tunnelName ?? ''];
  const fileOperations = c.operation === 'create' && c.configPath ? [{ path: c.configPath, action: 'create' as const, content: `# Generated by cloudflare-tunnel-kit\n`, requiresConfirmation: true }] : [];
  return { id: crypto.randomUUID(), createdAt: new Date().toISOString(), config: c, valid: validation.ok, argv, fileOperations, confirmations: fileOperations.length ? ['config-file'] : [], issues: validation.issues, summary: validation.ok ? `Ready to run: cloudflared ${argv.join(' ')}` : `${validation.issues.length} validation issue(s) must be fixed before execution.` };
}
